INSERT INTO sellers_info (user_id, photo_url, location) VALUES (1, 'http://dummyimage.com/143x100.png/dddddd/000000', 'Toronto');
INSERT INTO sellers_info (user_id, photo_url, location) VALUES (2, 'http://dummyimage.com/167x100.png/cc0000/ffffff', 'New York City');
INSERT INTO sellers_info (user_id, photo_url, location) VALUES (3, 'http://dummyimage.com/100x100.png/5fa2dd/ffffff', 'London');
INSERT INTO sellers_info (user_id, photo_url, location) VALUES (4, 'http://dummyimage.com/164x100.png/cc0000/ffffff', 'Oslo');
INSERT INTO sellers_info (user_id, photo_url, location) VALUES (5, 'http://dummyimage.com/227x100.png/cc0000/ffffff', 'Vancouver');
INSERT INTO sellers_info (user_id, photo_url, location) VALUES (6, 'http://dummyimage.com/108x100.png/5fa2dd/ffffff', 'Windsor');
INSERT INTO sellers_info (user_id, photo_url, location) VALUES (7, 'http://dummyimage.com/115x100.png/cc0000/ffffff', 'Guelph');
INSERT INTO sellers_info (user_id, photo_url, location) VALUES (8, 'http://dummyimage.com/107x100.png/5fa2dd/ffffff', 'Tokyo');
INSERT INTO sellers_info (user_id, photo_url, location) VALUES (9, 'http://dummyimage.com/227x100.png/ff4444/ffffff', 'Nashville');
INSERT INTO sellers_info (user_id, photo_url, location) VALUES (10, 'http://dummyimage.com/188x100.png/ff4444/ffffff', 'Louisville');
INSERT INTO sellers_info (user_id, photo_url, location) VALUES (11, 'http://dummyimage.com/239x100.png/dddddd/000000', 'Fresno');
INSERT INTO sellers_info (user_id, photo_url, location) VALUES (12, 'http://dummyimage.com/225x100.png/5fa2dd/ffffff', 'Phoenix');
INSERT INTO sellers_info (user_id, photo_url, location) VALUES (13, 'http://dummyimage.com/237x100.png/cc0000/ffffff', 'Fayetteville');
INSERT INTO sellers_info (user_id, photo_url, location) VALUES (14, 'http://dummyimage.com/243x100.png/ff4444/ffffff', 'San Diego');
INSERT INTO sellers_info (user_id, photo_url, location) VALUES (15, 'http://dummyimage.com/119x100.png/5fa2dd/ffffff', 'Los Angeles');
INSERT INTO sellers_info (user_id, photo_url, location) VALUES (16, 'http://dummyimage.com/162x100.png/dddddd/000000', 'Philadelphia');
INSERT INTO sellers_info (user_id, photo_url, location) VALUES (17, 'http://dummyimage.com/108x100.png/5fa2dd/ffffff', 'Chengji');
INSERT INTO sellers_info (user_id, photo_url, location) VALUES (18, 'http://dummyimage.com/130x100.png/ff4444/ffffff', 'Waterloo');
INSERT INTO sellers_info (user_id, photo_url, location) VALUES (19, 'http://dummyimage.com/157x100.png/ff4444/ffffff', 'Colombo');
INSERT INTO sellers_info (user_id, photo_url, location) VALUES (20, 'http://dummyimage.com/157x100.png/dddddd/000000', 'Moshenskoye');
INSERT INTO sellers_info (user_id, photo_url, location) VALUES (21, 'http://dummyimage.com/216x100.png/5fa2dd/ffffff', 'Cereté');
INSERT INTO sellers_info (user_id, photo_url, location) VALUES (22, 'http://dummyimage.com/215x100.png/5fa2dd/ffffff', 'Outeiro');
INSERT INTO sellers_info (user_id, photo_url, location) VALUES (23, 'http://dummyimage.com/103x100.png/ff4444/ffffff', 'São Joaquim da Barra');
INSERT INTO sellers_info (user_id, photo_url, location) VALUES (24, 'http://dummyimage.com/147x100.png/cc0000/ffffff', 'Boyeros');
INSERT INTO sellers_info (user_id, photo_url, location) VALUES (25, 'http://dummyimage.com/167x100.png/cc0000/ffffff', 'Toronto');
INSERT INTO sellers_info (user_id, photo_url, location) VALUES (26, 'http://dummyimage.com/212x100.png/ff4444/ffffff', 'Calape');
INSERT INTO sellers_info (user_id, photo_url, location) VALUES (27, 'http://dummyimage.com/117x100.png/cc0000/ffffff', 'Kutno');
INSERT INTO sellers_info (user_id, photo_url, location) VALUES (28, 'http://dummyimage.com/127x100.png/cc0000/ffffff', 'Ryazhsk');
INSERT INTO sellers_info (user_id, photo_url, location) VALUES (29, 'http://dummyimage.com/231x100.png/cc0000/ffffff', 'Ipameri');
