INSERT INTO reviews (transaction_id, rating, message) VALUES (1, 2, 'lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien');
INSERT INTO reviews (transaction_id, rating, message) VALUES (2, 5, 'nunc vestibulum ante ipsum primis in');
INSERT INTO reviews (transaction_id, rating, message) VALUES (3, 2, 'nisi volutpat eleifend donec ut');
INSERT INTO reviews (transaction_id, rating, message) VALUES (4, 2, 'vivamus tortor duis mattis egestas metus');
INSERT INTO reviews (transaction_id, rating, message) VALUES (5, 5, 'proin at turpis a pede posuere nonummy integer');
INSERT INTO reviews (transaction_id, rating, message) VALUES (6, 5, 'tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus');
INSERT INTO reviews (transaction_id, rating, message) VALUES (7, 3, 'justo etiam pretium iaculis justo in hac habitasse platea');
INSERT INTO reviews (transaction_id, rating, message) VALUES (8, 2, 'blandit non interdum in ante vestibulum ante ipsum primis in');
INSERT INTO reviews (transaction_id, rating, message) VALUES (9, 1, 'vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra');
INSERT INTO reviews (transaction_id, rating, message) VALUES (10, 4, 'praesent blandit nam nulla');
INSERT INTO reviews (transaction_id, rating, message) VALUES (11, 5, 'mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in');
INSERT INTO reviews (transaction_id, rating, message) VALUES (12, 1, 'suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris');
INSERT INTO reviews (transaction_id, rating, message) VALUES (13, 3, 'tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis vel');
INSERT INTO reviews (transaction_id, rating, message) VALUES (14, 4, 'lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio');
INSERT INTO reviews (transaction_id, rating, message) VALUES (15, 2, 'lacinia erat vestibulum sed');
INSERT INTO reviews (transaction_id, rating, message) VALUES (16, 2, 'ipsum dolor sit amet consectetuer adipiscing elit proin risus praesent lectus vestibulum');
INSERT INTO reviews (transaction_id, rating, message) VALUES (17, 5, 'quis libero nullam sit amet turpis elementum ligula');
INSERT INTO reviews (transaction_id, rating, message) VALUES (18, 4, 'ultrices posuere cubilia curae nulla dapibus dolor vel est donec');
INSERT INTO reviews (transaction_id, rating, message) VALUES (19, 4, 'ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam');
INSERT INTO reviews (transaction_id, rating, message) VALUES (20, 3, 'aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac');
INSERT INTO reviews (transaction_id, rating, message) VALUES (21, 1, 'vulputate justo');
INSERT INTO reviews (transaction_id, rating, message) VALUES (22, 5, 'est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut');
INSERT INTO reviews (transaction_id, rating, message) VALUES (23, 5, 'aliquet pulvinar sed nisl');
INSERT INTO reviews (transaction_id, rating, message) VALUES (24, 1, 'vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet');
INSERT INTO reviews (transaction_id, rating, message) VALUES (25, 3, 'tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam');
INSERT INTO reviews (transaction_id, rating, message) VALUES (26, 4, 'in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor');
INSERT INTO reviews (transaction_id, rating, message) VALUES (27, 5, 'in faucibus');
INSERT INTO reviews (transaction_id, rating, message) VALUES (28, 2, 'enim in tempor turpis nec euismod scelerisque quam turpis adipiscing');
INSERT INTO reviews (transaction_id, rating, message) VALUES (29, 3, 'mauris viverra diam vitae quam suspendisse potenti');
INSERT INTO reviews (transaction_id, rating, message) VALUES (30, 2, 'praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in');
INSERT INTO reviews (transaction_id, rating, message) VALUES (31, 3, 'sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio');
INSERT INTO reviews (transaction_id, rating, message) VALUES (32, 3, 'proin risus praesent lectus vestibulum quam');
INSERT INTO reviews (transaction_id, rating, message) VALUES (33, 4, 'sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed');
INSERT INTO reviews (transaction_id, rating, message) VALUES (34, 4, 'vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna');
INSERT INTO reviews (transaction_id, rating, message) VALUES (35, 3, 'vivamus vestibulum sagittis sapien cum sociis natoque penatibus et');
INSERT INTO reviews (transaction_id, rating, message) VALUES (36, 3, 'at turpis donec posuere metus vitae ipsum aliquam non mauris morbi');
INSERT INTO reviews (transaction_id, rating, message) VALUES (37, 2, 'in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis');
INSERT INTO reviews (transaction_id, rating, message) VALUES (38, 5, 'in est risus auctor sed tristique in tempus sit');
INSERT INTO reviews (transaction_id, rating, message) VALUES (39, 3, 'adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere');
INSERT INTO reviews (transaction_id, rating, message) VALUES (40, 2, 'et eros vestibulum ac est lacinia nisi venenatis');
INSERT INTO reviews (transaction_id, rating, message) VALUES (41, 3, 'nulla suspendisse potenti cras in');
INSERT INTO reviews (transaction_id, rating, message) VALUES (42, 1, 'viverra diam vitae quam suspendisse potenti nullam porttitor lacus');
INSERT INTO reviews (transaction_id, rating, message) VALUES (43, 5, 'orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum');
INSERT INTO reviews (transaction_id, rating, message) VALUES (44, 2, 'tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus');
INSERT INTO reviews (transaction_id, rating, message) VALUES (45, 4, 'sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel');
INSERT INTO reviews (transaction_id, rating, message) VALUES (46, 3, 'pede justo eu massa donec dapibus duis at velit eu');
INSERT INTO reviews (transaction_id, rating, message) VALUES (47, 3, 'sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl');
INSERT INTO reviews (transaction_id, rating, message) VALUES (48, 1, 'mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem');
INSERT INTO reviews (transaction_id, rating, message) VALUES (49, 3, 'a suscipit nulla elit ac nulla sed vel');
INSERT INTO reviews (transaction_id, rating, message) VALUES (50, 1, 'arcu libero rutrum');
INSERT INTO reviews (transaction_id, rating, message) VALUES (51, 5, 'turpis nec euismod scelerisque quam turpis');
INSERT INTO reviews (transaction_id, rating, message) VALUES (52, 5, 'integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero');
INSERT INTO reviews (transaction_id, rating, message) VALUES (53, 2, 'purus eu magna vulputate');
INSERT INTO reviews (transaction_id, rating, message) VALUES (54, 5, 'ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue');
INSERT INTO reviews (transaction_id, rating, message) VALUES (55, 1, 'ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor');
INSERT INTO reviews (transaction_id, rating, message) VALUES (56, 4, 'tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in');
INSERT INTO reviews (transaction_id, rating, message) VALUES (57, 4, 'duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus');
INSERT INTO reviews (transaction_id, rating, message) VALUES (58, 4, 'quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus');
INSERT INTO reviews (transaction_id, rating, message) VALUES (59, 3, 'nam dui proin leo odio porttitor');
INSERT INTO reviews (transaction_id, rating, message) VALUES (60, 2, 'eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in');
INSERT INTO reviews (transaction_id, rating, message) VALUES (61, 4, 'arcu sed');
INSERT INTO reviews (transaction_id, rating, message) VALUES (62, 5, 'luctus et ultrices posuere cubilia curae nulla');
INSERT INTO reviews (transaction_id, rating, message) VALUES (63, 2, 'adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere');
INSERT INTO reviews (transaction_id, rating, message) VALUES (64, 1, 'sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus');
INSERT INTO reviews (transaction_id, rating, message) VALUES (65, 5, 'porttitor lorem id ligula suspendisse');
INSERT INTO reviews (transaction_id, rating, message) VALUES (66, 1, 'suspendisse potenti cras in purus eu magna vulputate luctus cum');
INSERT INTO reviews (transaction_id, rating, message) VALUES (67, 5, 'vestibulum ante ipsum primis in faucibus orci');
INSERT INTO reviews (transaction_id, rating, message) VALUES (68, 3, 'ut rhoncus aliquet pulvinar sed');
INSERT INTO reviews (transaction_id, rating, message) VALUES (69, 3, 'quisque porta volutpat erat quisque');
INSERT INTO reviews (transaction_id, rating, message) VALUES (70, 2, 'etiam faucibus cursus urna ut tellus nulla ut erat');
INSERT INTO reviews (transaction_id, rating, message) VALUES (71, 1, 'justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate');
INSERT INTO reviews (transaction_id, rating, message) VALUES (72, 5, 'tellus in sagittis dui vel nisl duis ac nibh fusce');
INSERT INTO reviews (transaction_id, rating, message) VALUES (73, 2, 'porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non');
INSERT INTO reviews (transaction_id, rating, message) VALUES (74, 5, 'maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque');
INSERT INTO reviews (transaction_id, rating, message) VALUES (75, 5, 'vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla');
INSERT INTO reviews (transaction_id, rating, message) VALUES (76, 3, 'ipsum');
INSERT INTO reviews (transaction_id, rating, message) VALUES (77, 2, 'vitae nisi nam ultrices libero non mattis pulvinar nulla pede');
INSERT INTO reviews (transaction_id, rating, message) VALUES (78, 2, 'vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue');
INSERT INTO reviews (transaction_id, rating, message) VALUES (79, 3, 'ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam');
INSERT INTO reviews (transaction_id, rating, message) VALUES (80, 4, 'vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae');
INSERT INTO reviews (transaction_id, rating, message) VALUES (81, 2, 'sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi');
INSERT INTO reviews (transaction_id, rating, message) VALUES (82, 5, 'ipsum praesent');
INSERT INTO reviews (transaction_id, rating, message) VALUES (83, 2, 'nullam varius nulla facilisi cras non');
INSERT INTO reviews (transaction_id, rating, message) VALUES (84, 5, 'venenatis lacinia aenean sit amet justo');
INSERT INTO reviews (transaction_id, rating, message) VALUES (85, 5, 'nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra');
INSERT INTO reviews (transaction_id, rating, message) VALUES (86, 1, 'purus aliquet at feugiat non pretium quis lectus suspendisse potenti in');
INSERT INTO reviews (transaction_id, rating, message) VALUES (87, 1, 'risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in');
INSERT INTO reviews (transaction_id, rating, message) VALUES (88, 5, 'at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a');
INSERT INTO reviews (transaction_id, rating, message) VALUES (89, 4, 'tortor sollicitudin mi sit amet lobortis');
INSERT INTO reviews (transaction_id, rating, message) VALUES (90, 3, 'mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante');
INSERT INTO reviews (transaction_id, rating, message) VALUES (91, 1, 'magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in');
INSERT INTO reviews (transaction_id, rating, message) VALUES (92, 3, 'congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin');
INSERT INTO reviews (transaction_id, rating, message) VALUES (93, 2, 'in est risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl');
INSERT INTO reviews (transaction_id, rating, message) VALUES (94, 3, 'pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar');
INSERT INTO reviews (transaction_id, rating, message) VALUES (95, 3, 'eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget');
INSERT INTO reviews (transaction_id, rating, message) VALUES (96, 5, 'aliquam lacus morbi quis tortor id nulla ultrices aliquet');
INSERT INTO reviews (transaction_id, rating, message) VALUES (97, 5, 'in hac habitasse platea dictumst maecenas ut massa');
INSERT INTO reviews (transaction_id, rating, message) VALUES (98, 3, 'in hac habitasse platea dictumst maecenas ut massa quis augue');
INSERT INTO reviews (transaction_id, rating, message) VALUES (99, 3, 'tortor id nulla');
INSERT INTO reviews (transaction_id, rating, message) VALUES (100, 4, 'proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae');
